### ISSUE TITLE
Add a CORS config

### ISSUE THREAD

**Issue by jozefcipa** [jozefcipa/novus#8]
In your `novus.yml` config, when defining routes, you could optionally also enable CORS configuration to avoid those annoying errors while developing locally.

Example of how it could look:

```
appName: my-awesome-app
routes:
  - domain: my-frontend.test
    upstream: http://localhost:3000
  - domain: my-api.test
    upstream: http://localhost:4000
    cors: true
```

This would be then directly applied in the NGINX config as `Access-Control-Allow-Origin *`, similarly to this answer https://serverfault.com/a/979627
